# Generated by Django 4.2.7 on 2023-12-15 18:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_likepost_username_likepost_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
