version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/postgresql/data
      - ./project/media/profile_images:/code/media/profile_images/
      - ./project/media/post_images:/code/media/post_images/
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    env_file:
      - ./.env
    ports:
      - "5431:5432"
    volumes:
      - data:/var/lib/postgresql/data
    hostname: database
volumes:
  data:
    driver: local
