version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/code
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    environment:
      DB_NAME: social-media
      DB_USER: postgres
      DB_PASS: abcdefgh

    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5431:5432"
    env_file:
      - ./.env
    # restart: always
    environment:
      POSTGRES_DB: social-media
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcdefgh
    volumes:
      - ./data:/var/lib/postgresql/data
    hostname: database

