# Generated by Django 4.2.7 on 2023-12-15 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_followersmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
        migrations.AddField(
            model_name='profiledatamodel',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
