# Generated by Django 4.2.7 on 2023-12-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profiledatamodel_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatamodel',
            name='profileimg',
            field=models.ImageField(blank=True, default='images/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
