# Generated by Django 4.2.7 on 2023-12-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profiledatamodel_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatamodel',
            name='profileimg',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
